### ISSUE TITLE
Create readme

### ISSUE THREAD

**Issue by sarahjameson** [liamthetate/hackathon#7]
Create an outline of readme and start on user stories

**Comment by dandavies23** [comment]
[Wrote this ](https://github.com/liamthetate/hackathon/issues/4)for the rules for the game (when we work out what they are) but it might help kick off the README?

**Comment by sarahjameson** [comment]
Yes, love that for the start, Dan! 🔥🔥

**Comment by dandavies23** [comment]
# LIONOIL: Dunking on the Ceiling

[Dunking on the Ceiling picture - just use the black one]
-------

## Commodore[s] 64s
-------

<<<<<<< HEAD

### Table of Contents

- [Introduction](#introduction)
- [UX](#ux)
- [Features](#features)
- [Technologies Used](#technologies-used)
- [Testing](#testing)
- [Deployment](#deployment)
- [Credits](#credits)


### Introduction

Hello? 
-------

Is it retro-game you’re lookin’ for? LIONOIL is a platform game with a 180 degree twist. Inspired by the classic 1980s platform games and [Lionel Richie's Dancing On The Ceiling ](https://m.youtube.com/watch?v=xgT8uwDGLWk)and [TENET](https://www.themoviedb.org/movie/577922-tenet).


The Game
--------

Lionel Richtea was happy living his best life - all day and all night long.

But, say _what is happening here? Something’s going on that’s not quite clear_… 

Lionel is blasted into the underworld of Twisted Disco-Pop where some evil puppet-master LIONOIL is forcing Lionel to battle the bad guys [link to bad guys cards] and collect biscuits he needs to dunk his way out.

Do you have what it takes to guide Lionel across the floors, walls and ceiling of the Twisted Disco-Pop dimension?

### UX

#### Potential Users
* People looking for something fun to do in their free time
* Adults or children alike can play as it isn't overly complicated
* Lionel Richie fans can play as him in a fun setting and enjoy the different cultural components to the game
* Competitive side is appealed to through use of leaderboard and scores

The website will appeal to these users through:
* A quick start
* Clear instructions
* Fun theme inspired by Lionel Richie and other 80's icons
* Well-thought out UX that helps users play game

#### User Stories

##### First Time Visitor Goals
* As a first time visitor, I want to understand the main purpose of site
* As a first time visitor, I want to know where the game's instructions are on the site
* As a first time visitor, I want to be excited by the visuals and eager to start playing

##### Returning Visitor Goals
* As a returning visitor, I want to view the leaderboard and logged scores

##### Frequent Visitor Goals
* As a frequent visitor, I want to see if anyone has beat my score since I last played
* As a frequent visitor,

#### Design
The design of that game is inspired by the classic 8-bit platform games of the 1980s. Although much of the original framework is Mario (using Kaboom). The tone and playful tweaks have more in line with the UK 'bedroom coders' such as Codemasters using platforms for use on the Sinclair Spectrum and the Commodore 64.   

The twist of the game is that the screen orientation changes which disorientates the user. The perfect hero character is  1980s singer and ceiling-dancer Lionel Richie. 

Other design touchpoints are inspired by Lionel Richie's early back catalogue and the meme's of "Lionel Richtea" and Richie's massive clay head in hello. 

![LionelTeaMug](https://user-images.githubusercontent.com/566086/128713101-c2f8f8ce-8743-41b9-9632-a6e01af90935.jpg)

![LionelRichie-DOTC](https://user-images.githubusercontent.com/566086/128713137-0ae472ff-9d89-4df6-b4de-a13ee7641c26.jpeg)



#### Wireframes

To do

### Features

To do

### Technologies Used

#### Languages Used

* [HTML5](https://en.wikipedia.org/wiki/HTML5)
* [CSS](https://en.wikipedia.org/wiki/CSS)
* [JavaScript](https://en.wikipedia.org/wiki/JavaScript)

#### Frameworks, Libraries and Programs Used

To do

### Testing

To do

### Deployment

To do

### Credits

To do
=======
## this another test to see if the main is protected
This is a version revision to test things

>>>>>>> 55f63eab8e0b588af0e802d8577154b81bbf0940
